matrix:
  include:
  - os: osx
    osx_image: xcode8.3

language: node_js

before_script:
- yarn add global node-sass
- yarn install

script:
- travis_wait yarn dist

node_js:
- '9'

cache: yarn

notifications:
  email: false
